#pragma once
#include <stdint.h>
#include "screen.h"

// A packed 1bpp bitmap, row-major with bit 7 of each byte the leftmost pixel.
// Sprites are generated by tools/png2bitmap.py; nothing here allocates.
namespace gfx {

struct Sprite {
  int w;
  int h;
  const uint8_t *bits;

  void blit(Screen &s, int x, int y) const {
    const int stride = (w + 7) / 8;
    for (int j = 0; j < h; j++)
      for (int i = 0; i < w; i++)
        if (bits[j * stride + (i >> 3)] & (0x80 >> (i & 7))) s.pixel(x + i, y + j, true);
  }

  void blitCentered(Screen &s) const { blit(s, (W - w) / 2, (H - h) / 2); }
};

// The title-screen ship, 48x48, decoded from ship.png.
extern const Sprite SHIP;

}  // namespace gfx
