#!/usr/bin/env python3
"""Convert a PNG to a packed 1bpp sprite for gfx::Screen.

No third-party deps: decodes PNG with zlib, box-downscales to the requested
size, thresholds to mono, and emits a C array in row-major MSB-first order
(bit 7 of each byte is the leftmost pixel), which is what Sprite::blit reads.

    tools/png2bitmap.py ship.png 48 48 SHIP > src/game/ship_sprite.inc
"""
import sys, zlib, struct


def read_png(path):
    d = open(path, 'rb').read()
    assert d[:8] == b'\x89PNG\r\n\x1a\n', 'not a PNG'
    pos, idat, plte, trns, hdr = 8, b'', None, None, None
    while pos < len(d):
        ln, typ = struct.unpack('>I4s', d[pos:pos + 8])
        body = d[pos + 8:pos + 8 + ln]
        if typ == b'IHDR':
            hdr = struct.unpack('>IIBBBBB', body)
        elif typ == b'PLTE':
            plte = body
        elif typ == b'tRNS':
            trns = body
        elif typ == b'IDAT':
            idat += body
        elif typ == b'IEND':
            break
        pos += 12 + ln
    w, h, depth, ctype, comp, filt, interlace = hdr
    assert depth == 8 and interlace == 0, f'unsupported PNG: depth={depth} interlace={interlace}'
    nch = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}[ctype]
    raw = zlib.decompress(idat)
    stride = w * nch
    out, prev = [], bytearray(stride)
    p = 0
    for _ in range(h):
        f = raw[p]; p += 1
        line = bytearray(raw[p:p + stride]); p += stride
        for i in range(stride):
            a = line[i - nch] if i >= nch else 0
            b = prev[i]
            c = prev[i - nch] if i >= nch else 0
            x = line[i]
            if f == 1: x += a
            elif f == 2: x += b
            elif f == 3: x += (a + b) >> 1
            elif f == 4:
                pp = a + b - c
                pa, pb, pc = abs(pp - a), abs(pp - b), abs(pp - c)
                x += a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
            line[i] = x & 0xFF
        out.append(line); prev = line

    # -> (luma, alpha) per pixel
    px = []
    for line in out:
        row = []
        for x in range(w):
            if ctype == 3:
                idx = line[x]
                r, g, b = plte[idx * 3:idx * 3 + 3]
                a = trns[idx] if trns and idx < len(trns) else 255
            elif ctype == 0:
                r = g = b = line[x]; a = 255
            elif ctype == 4:
                r = g = b = line[x * 2]; a = line[x * 2 + 1]
            elif ctype == 2:
                r, g, b = line[x * 3:x * 3 + 3]; a = 255
            else:
                r, g, b, a = line[x * 4:x * 4 + 4]
            row.append(((r * 299 + g * 587 + b * 114) // 1000, a))
        px.append(row)
    return w, h, px


def main():
    path, ow, oh, name = sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), sys.argv[4]
    w, h, px = read_png(path)

    # Box filter down to ow x oh, tracking coverage of "ink" (dark & opaque).
    bits = []
    for oy in range(oh):
        row = []
        for ox in range(ow):
            x0, x1 = ox * w // ow, max(ox * w // ow + 1, (ox + 1) * w // ow)
            y0, y1 = oy * h // oh, max(oy * h // oh + 1, (oy + 1) * h // oh)
            ink = tot = 0
            for y in range(y0, y1):
                for x in range(x0, x1):
                    lum, a = px[y][x]
                    tot += 1
                    if a > 127 and lum < 128:
                        ink += 1
            row.append(1 if ink * 2 >= tot else 0)  # majority ink -> lit
        bits.append(row)

    stride = (ow + 7) // 8
    data = bytearray(stride * oh)
    for y in range(oh):
        for x in range(ow):
            if bits[y][x]:
                data[y * stride + (x >> 3)] |= 0x80 >> (x & 7)

    print(f'// Generated by tools/png2bitmap.py from {path} -- do not edit.')
    print(f'// {ow}x{oh}, 1bpp, row-major, MSB = leftmost pixel. '
          f'{len(data)} bytes = {len(data) * 2} hex characters.')
    print(f'constexpr int {name}_W = {ow};')
    print(f'constexpr int {name}_H = {oh};')
    print(f'const uint8_t {name}_BITS[{len(data)}] = {{')
    for i in range(0, len(data), 12):
        print('  ' + ' '.join(f'0x{b:02X},' for b in data[i:i + 12]))
    print('};')


main()
