// Drives the WASM build of the game core and paints its two Screen buffers
// into two independent canvases -- one per physical panel.

export {};  // make this a module so top-level await is allowed

interface Sim {
  HEAPU8: Uint8Array;
  _sim_begin(): void;
  _sim_set_input(mask: number): void;
  _sim_set_page(page: number): void;
  _sim_page(): number;
  _sim_set_link(state: number): void;
  _sim_set_self_peer(id: number): void;
  _sim_receive(v: number, seq: number, src: number, dst: number,
               t: number, a: number, b: number): void;
  _sim_take_outbound(): number;
  _sim_my_turn(): number;
  _sim_aim_col(): number;
  _sim_aim_row(): number;
  _sim_in_flight(): number;
  _sim_set_hit_ship(ship: number): void;
  _sim_lobby_name_max(): number;
  _sim_clear_rooms(): void;
  _sim_set_room(n: number, count: number, yours: number): void;
  _sim_set_names(): void;
  _sim_room_a_buf(): number;
  _sim_room_b_buf(): number;
  _sim_take_room_join(): number;
  _sim_take_room_leave(): number;
  _sim_set_my_room(n: number): void;
  _sim_room_count(): number;
  _sim_tick(nowMs: number): void;
  _sim_top(): number;
  _sim_bottom(): number;
  _sim_buf_size(): number;
  _sim_width(): number;
  _sim_height(): number;
}

// Indirect specifier: sim.js is generated by emcc at build time, so there is
// nothing for tsc to resolve at check time.
const SIM_URL = "./sim.js";
const createSim = (await import(SIM_URL)).default as () => Promise<Sim>;
const sim = await createSim();

const W = sim._sim_width();
const H = sim._sim_height();

// --- input -----------------------------------------------------------------
const M = { up: 1, right: 2, down: 4, left: 8, center: 16 };

const KEYS: Record<string, number> = {
  ArrowUp: M.up, ArrowRight: M.right, ArrowDown: M.down, ArrowLeft: M.left,
  KeyW: M.up, KeyD: M.right, KeyS: M.down, KeyA: M.left,
  Space: M.center, Enter: M.center,
};

const held = new Set<string>();

// A key pressed while the name box has focus is a letter being typed, not a
// move: W, A, S, D, space and Enter are all in the map below, so swallowing
// them here is what made half the alphabet impossible to type.
const typing = (e: Event) => {
  const t = e.target;
  return t instanceof HTMLInputElement || t instanceof HTMLTextAreaElement ||
         t instanceof HTMLSelectElement;
};

addEventListener("keydown", (e) => {
  if (typing(e)) return;
  if (!(e.code in KEYS)) return;
  e.preventDefault();  // stop arrows/space from scrolling the page
  held.add(e.code);
});
addEventListener("keyup", (e) => {
  if (typing(e)) return;
  if (e.code in KEYS) { e.preventDefault(); held.delete(e.code); }
});
addEventListener("blur", () => held.clear());  // don't stick keys on tab-out

// ---- touch: the same five buttons, drawn with a finger --------------------
//
// A phone has no 5-way switch, so the gestures stand in for one: a swipe is
// the direction it went, a tap is centre, and holding still is centre held --
// which is what the leave countdown reads. The core is never told about any
// of this; it sees the same five levels it sees from the switch or the keys,
// so a game played with a thumb is the same game.
const touched = { up: false, right: false, down: false, left: false, centre: false };

// How far a finger must travel to be a swipe rather than a tap, and how long
// it must sit still to be a hold rather than a tap. 24px is about a fingertip
// of slop; 250ms is comfortably under the double press, so tapping twice to
// place a ship never becomes a hold.
const SWIPE_PX = 24;
const HOLD_TOUCH_MS = 250;

// A swipe is a step, not a level: it sets the direction for one repeat of the
// cursor and then lets go, which is what a flick means. Holding a direction
// is a swipe followed by keeping the finger out there, handled by re-arming
// from the new origin.
const STEP_HOLD_MS = 140;

function pulse(key: "up" | "right" | "down" | "left" | "centre", ms: number) {
  touched[key] = true;
  setTimeout(() => { touched[key] = false; }, ms);
}

function touchControls(el: HTMLElement) {
  let x0 = 0, y0 = 0, startedAt = 0, moved = false, holdTimer = 0;

  const end = () => {
    clearTimeout(holdTimer);
    if (touched.centre) {          // a hold, ended by lifting the finger
      touched.centre = false;
      return;
    }
    if (!moved && performance.now() - startedAt < HOLD_TOUCH_MS) {
      pulse("centre", 120);        // a tap is a press
    }
  };

  el.addEventListener("touchstart", (e) => {
    const t = e.changedTouches[0];
    x0 = t.clientX; y0 = t.clientY;
    startedAt = performance.now();
    moved = false;
    e.preventDefault();            // no scrolling, no double-tap zoom
    // Still after a moment: the finger is holding the button down, which is
    // what the countdown to leaving a match reads.
    holdTimer = window.setTimeout(() => {
      if (!moved) touched.centre = true;
    }, HOLD_TOUCH_MS);
  }, { passive: false });

  el.addEventListener("touchmove", (e) => {
    const t = e.changedTouches[0];
    const dx = t.clientX - x0, dy = t.clientY - y0;
    if (Math.abs(dx) < SWIPE_PX && Math.abs(dy) < SWIPE_PX) return;
    e.preventDefault();
    moved = true;
    clearTimeout(holdTimer);
    touched.centre = false;        // a swipe is not a press
    // The bigger movement wins, so a diagonal drag is read as the direction
    // it mostly went rather than as two directions at once.
    if (Math.abs(dx) > Math.abs(dy)) pulse(dx > 0 ? "right" : "left", STEP_HOLD_MS);
    else pulse(dy > 0 ? "down" : "up", STEP_HOLD_MS);
    // Re-armed from here, so keeping the finger moving keeps stepping.
    x0 = t.clientX; y0 = t.clientY;
  }, { passive: false });

  el.addEventListener("touchend", (e) => { e.preventDefault(); end(); }, { passive: false });
  el.addEventListener("touchcancel", () => { clearTimeout(holdTimer); touched.centre = false; });
}

function inputMask(): number {
  let m = 0;
  for (const code of held) m |= KEYS[code];
  if (touched.up) m |= M.up;
  if (touched.right) m |= M.right;
  if (touched.down) m |= M.down;
  if (touched.left) m |= M.left;
  if (touched.centre) m |= M.center;
  return m;
}

// --- pages (browser only) --------------------------------------------------
// The core owns which page it is on; this only exists so the host can put it
// on one -- the lobby list when a match ends, placement when one starts.
// Must match game::Page in src/game/game.h: sim_set_page casts the number
// straight to that enum, so the two lists are one interface in two files.
const PAGE = {
  start: 0,
  connecting: 1,
  place: 2,
  starting: 3,
  match: 4,
  hit: 5,
  miss: 6,
  sunk: 7,
  over: 8,
  waiting: 9,
  rooms: 10,
} as const;

// Mirrors game::Link in src/game/game.h.
const LINK = { offline: 0, connecting: 1, online: 2 } as const;

const el = <T extends HTMLElement>(id: string, ctor: new () => T): T => {
  const e = document.getElementById(id);
  if (!(e instanceof ctor)) throw new Error(`missing #${id}`);
  return e;
};

function selectPage(page: number) {
  sim._sim_set_page(page);
}

// ---- how to play ----
// The five-way switch the boards have, drawn as it sits under a thumb, with
// what each press does written underneath. It is a dialog rather than a line
// of text under the screens because it is read once and then never again.
{
  const modal = el("controlsModal", HTMLDivElement);
  const show = (open: boolean) => { modal.hidden = !open; };
  el("btn-controls", HTMLButtonElement).addEventListener("click", () => show(true));
  el("btn-controls-close", HTMLButtonElement).addEventListener("click", () => show(false));
  modal.addEventListener("click", (e) => { if (e.target === modal) show(false); });
  addEventListener("keydown", (e) => { if (e.key === "Escape") show(false); });
}

// ---- reset ----
// sim_begin() re-runs Game::begin(), which clears the fleet, the tracking
// grid and every cursor -- the same call the firmware makes at power-on, so a
// reset here leaves the core in exactly the state a fresh boot would.
export function resetGame() {
  sim._sim_begin();
  selectPage(PAGE.start);
  // Give the seat up too. Resetting the core while a token was still live
  // left the tab polling a match it had erased, with nothing to put it back
  // on the lobby list.
  if (peerToken) {
    void leaveRoom();
  } else if (!roomLoopRunning) {
    void roomLoop();
  }
}

el("btn-reset", HTMLButtonElement).addEventListener("click", resetGame);

// ---- the name box --------------------------------------------------------
//
// A name can be changed while you are in the lobby and not while you are
// playing: it is who the relay thinks is at the table, and swapping it under
// a running match would leave the other player looking at somebody who no
// longer exists. So the box shadows out the moment a game starts.
//
// Changing it starts you over, which is what the warning says. There is no
// halfway version of this -- the name travels with the join, the seat and the
// board -- so the honest implementation goes back to the beginning and comes
// in again as that player.
function wireNameBox() {
  const box = el("btn-name", HTMLInputElement);
  const save = el("btn-save", HTMLButtonElement);
  const warn = el("nameWarn", HTMLParagraphElement);

  // Whether the player has typed in it. Tracked rather than inferred from a
  // comparison with the current name, so filling the box in from the name we
  // already know does not look like an edit -- which is what left it empty.
  let dirty = false;

  const refresh = () => {
    const playing = peerToken !== "";
    box.disabled = playing;
    if (!dirty && document.activeElement !== box) box.value = playerName;
    const show = dirty && !playing && cleanName(box.value).trim() !== playerName;
    save.hidden = !show;
    warn.hidden = !show;
  };

  box.addEventListener("input", () => {
    const fixed = cleanName(box.value);
    if (fixed !== box.value) {
      const at = Math.min(box.selectionStart ?? fixed.length, fixed.length);
      box.value = fixed;
      box.setSelectionRange(at, at);
    }
    dirty = true;
    refresh();
  });

  save.addEventListener("click", async () => {
    const name = cleanName(box.value).trim() || "player";
    store.set(localStorage, "playerName", name);
    // Stand up from whatever lobby this player is sitting in first, so the
    // row does not keep showing a name nobody answers to, then start again.
    try {
      await fetch("/v1/rooms/leave", { method: "POST", headers: idHeaders() });
    } catch {
      /* the reload puts us back in the lobby either way */
    }
    location.reload();
  });

  nameBoxRefresh = refresh;
  refresh();
}

// ---- the link ----
// The relay serves this page, so it is always at the same origin and needs no
// address configuring. Claiming a seat is what tells the core the link is up;
// the connecting page then moves on by itself.
//
// A failure here is not fatal and must not be: with no relay running the page
// still plays perfectly well on its own, so the core is told Offline and the
// connecting page says so and invites a press to carry on.
let peerToken = "";
let selfPeer = 0;

// ---- who this player is -------------------------------------------------
//
// A UUID made once and kept, so the server can tell two players apart when
// they pick the same name -- and can recognise this one again after a reload,
// which is what makes reconnecting to a running match possible at all. The
// name is only a label.
// Storage that cannot throw. A private window, or a browser set to block site
// data, makes every one of these calls raise -- and at module level that
// stops the whole page evaluating, so neither canvas is ever created and the
// tab is blank with only a console line to explain it. The game plays
// perfectly well with nothing remembered; it does not play at all if reading
// a preference can kill the module.
const store = {
  get(where: Storage, key: string): string | null {
    try {
      return where.getItem(key);
    } catch {
      return null;
    }
  },
  set(where: Storage, key: string, value: string) {
    try {
      where.setItem(key, value);
    } catch {
      /* nothing is remembered; everything still works */
    }
  },
  drop(where: Storage, key: string): boolean {
    try {
      where.removeItem(key);
      return true;
    } catch {
      return false;
    }
  },
};

// A v4 UUID, without requiring a secure context.
//
// crypto.randomUUID() exists only on HTTPS and localhost. The relay now binds
// the whole WiFi, and a phone opening the page by the laptop's LAN address is
// therefore in an INSECURE context -- where that function is simply not
// defined, and the page died on the line that called it before either canvas
// was drawn. crypto.getRandomValues() carries no such restriction, so the
// bytes come from there and only the formatting is done here; Math.random is
// the last resort, and being able to play is worth more than the quality of
// an id that only has to be different from the other players in the room.
function makePlayerId(): string {
  const bytes = new Uint8Array(16);
  if (typeof crypto !== "undefined" && typeof crypto.getRandomValues === "function") {
    crypto.getRandomValues(bytes);
  } else {
    for (let i = 0; i < bytes.length; i++) bytes[i] = Math.floor(Math.random() * 256);
  }
  bytes[6] = (bytes[6] & 0x0f) | 0x40;   // version 4
  bytes[8] = (bytes[8] & 0x3f) | 0x80;   // variant 1
  const hex = [...bytes].map((b) => b.toString(16).padStart(2, "0"));
  return [
    hex.slice(0, 4).join(""),
    hex.slice(4, 6).join(""),
    hex.slice(6, 8).join(""),
    hex.slice(8, 10).join(""),
    hex.slice(10, 16).join(""),
  ].join("-");
}

const PLAYER_ID = (() => {
  // Per TAB, not per browser. localStorage is shared by every tab of the same
  // origin, so two tabs there are one player as far as the relay can tell --
  // which is exactly why only the most recently opened one ever appeared in
  // the list. sessionStorage is per tab and still survives a reload, which is
  // what reconnecting to a running match needs.
  const saved = store.get(sessionStorage, "playerId");
  if (saved) return saved;
  const made = typeof crypto !== "undefined" && typeof crypto.randomUUID === "function"
    ? crypto.randomUUID()
    : makePlayerId();
  store.set(sessionStorage, "playerId", made);
  return made;
})();

let playerName = store.get(localStorage, "playerName") ?? "";
// Set once the name box exists: the frame loop calls it so the box tracks the
// game -- filled in when the name is known, shadowed out once a match starts.
let nameBoxRefresh: () => void = () => {};
// Red and black are gone from here entirely: they are an ESP32 label, carried
// in a board's own name, because a board has no keyboard to be named with.

const idHeaders = () => ({ "X-Player-Id": PLAYER_ID });

// One name per tab, not per application. The relay lets a client take back a
// seat it already holds -- which is what makes reloading, or reflashing the
// board, work rather than finding the table full of yourself -- and that only
// behaves if two tabs are two different clients.
const clientName = `browser-${Math.random().toString(16).slice(2, 6)}`;

// Keep trying, the way the firmware does. A tab opened before the relay is
// started, or while both seats are briefly held by a stale client, joins as
// soon as one is free rather than being stuck offline until it is reloaded.
// Until then the core is told Offline, so the connecting page says so and
// stays pressable.
// ---- the name modal -----------------------------------------------------
// Asked before anything connects, because the name travels with this player
// to the other side: the connection cannot be made without it.
// What a name may be. The panels draw 16 characters and no more, and the name
// travels to a board inside a line- and pipe-delimited text protocol -- so a
// newline or a pipe in a name is a name that can forge a line of that
// protocol. The relay enforces this too, and has to: a page is not a
// gatekeeper. Doing it here as well is so the player sees the name they will
// actually be given rather than discovering it on someone else's panel.
const NAME_MAX = 16;

function cleanName(raw: string): string {
  let out = "";
  for (const ch of raw) {
    const code = ch.codePointAt(0) ?? 0;
    if (code < 0x20 || code === 0x7f || ch === "|") continue;
    out += ch;
    if ([...out].length >= NAME_MAX) break;
  }
  return out;
}

function askName(): Promise<void> {
  return new Promise((resolve) => {
    const modal = el("nameModal", HTMLDivElement);
    const form = el("nameForm", HTMLFormElement);
    const input = el("nameInput", HTMLInputElement);
    const hint = el("nameHint", HTMLParagraphElement);
    input.maxLength = NAME_MAX;
    input.value = cleanName(playerName);
    modal.hidden = false;
    input.focus();

    // Corrected as it is typed rather than refused on submit: a paste that
    // carries a newline is fixed in front of the player, who then sees what
    // their name is going to be.
    input.addEventListener("input", () => {
      const fixed = cleanName(input.value);
      if (fixed !== input.value) {
        const at = Math.min(input.selectionStart ?? fixed.length, fixed.length);
        input.value = fixed;
        input.setSelectionRange(at, at);
        hint.textContent = `Names are ${NAME_MAX} characters of plain text.`;
        hint.classList.add("bad");
        return;
      }
      hint.classList.remove("bad");
      const left = NAME_MAX - [...fixed].length;
      hint.textContent = left <= 4
        ? `${left} character${left === 1 ? "" : "s"} left.`
        : `Up to ${NAME_MAX} characters \u2014 that is what a panel line holds.`;
    });

    form.addEventListener("submit", (e) => {
      e.preventDefault();
      playerName = cleanName(input.value).trim() || "player";
      store.set(localStorage, "playerName", playerName);
      modal.hidden = true;
      // Focus has to leave the field, not just the screen. Keys typed while
      // an input has focus are letters, not moves -- that is what stops WASD
      // being unusable in the name box -- so a hidden box that kept focus
      // swallowed every press of the game that followed it.
      input.blur();
      if (document.activeElement instanceof HTMLElement) document.activeElement.blur();
      resolve();
    });
  });
}

// ---- the five rooms -----------------------------------------------------
// Drawn by the CORE on the top panel, not by this page: picking a lobby is
// part of the game, so it is the same screen with the same cursor on a board
// and in a browser. The only thing a browser player does that a board cannot
// is type their name.
//
// A full room is refused by the relay, which is the check that counts -- two
// clients pressing centre on the same row in the same instant is what no
// amount of drawing can cover.
type RoomRow = { n: number; players: string[]; yours?: boolean };

let myRoom = 0;

function writeName(buf: number, name: string) {
  const max = sim._sim_lobby_name_max();
  const bytes = new TextEncoder().encode(name).subarray(0, max);
  sim.HEAPU8.set(bytes, buf);
  sim.HEAPU8[buf + bytes.length] = 0;
}

function pushRooms(rooms: RoomRow[]) {
  sim._sim_clear_rooms();
  for (const r of rooms) {
    writeName(sim._sim_room_a_buf(), r.players[0] ?? "");
    writeName(sim._sim_room_b_buf(), r.players[1] ?? "");
    sim._sim_set_room(r.n, r.players.length, r.yours ? 1 : 0);

    // Both players of OUR lobby, by name, so the verdict can say whose win it
    // is. "WIN" is the same word on both panels; a name is not.
    if (r.n === myRoom && r.players.length === 2) {
      const them = r.players.find((n) => n !== playerName) ?? r.players[1];
      writeName(sim._sim_room_a_buf(), playerName);
      writeName(sim._sim_room_b_buf(), them);
      sim._sim_set_names();
    }
  }
  sim._sim_set_my_room(myRoom);
}

let roomLoopRunning = false;

async function roomLoop() {
  if (roomLoopRunning) return;   // one loop, however many ways back in there are
  roomLoopRunning = true;
  try {
    await watchRooms();
  } finally {
    roomLoopRunning = false;
  }
}

async function watchRooms() {
  for (;;) {
    if (peerToken) return;
    // From the title, and from the connecting page too. A press that lands
    // before the first poll answers takes the core off the title by itself --
    // it asks ONLINE or OFFLINE and centre answers it -- and the connecting
    // page then waits for a handshake that the browser never performs, since
    // the browser is paired by the lobby rather than by Join/Ack. Without
    // this, an early press left the tab watching water for ever.
    const on = sim._sim_page();
    if (on === PAGE.start || on === PAGE.connecting) selectPage(PAGE.rooms);
    try {
      const res = await fetch("/v1/rooms", { headers: idHeaders() });
      if (res.ok) {
        const body = await res.json();
        myRoom = body.you ?? 0;
        pushRooms((body.rooms ?? []) as RoomRow[]);
        // Paired. The seat and the token arrive with it, which is the moment
        // this stops being a lobby and becomes a game.
        // A token is what makes it a match: the relay pairs players and hands
        // out seats in two steps, and taking "matched" without one leaves the
        // page on a board it cannot play.
        if (body.matched && body.token && !peerToken) {
          peerToken = body.token;
          selfPeer = body.seat === "b" ? 2 : 1;
          sim._sim_set_self_peer(selfPeer);
          sim._sim_set_link(LINK.online);
          // A match already in progress in this lobby is one we are walking
          // back into: the relay hands the board back and we are put down
          // where we left off. A fresh match has no board to hand back, and
          // starts from placement.
          const restored = await reconnect();
          if (!restored) selectPage(PAGE.place);
          void pollForever();
          return;
        }
      }
    } catch {
      /* the relay being away is already reported by the connecting page */
    }
    await new Promise((r) => setTimeout(r, 1000));
  }
}

// True once the relay knows who we are. A press that lands before that -- the
// player is quicker than the first round trip, which is easy -- is remembered
// rather than dropped: the relay refuses a room join from a player it has not
// been introduced to, and silently losing the press reads as a dead button.
let known = false;
let pendingJoin = 0;

async function joinRoom(n: number) {
  if (!known) {
    pendingJoin = n;
    return;
  }
  try {
    const res = await fetch(`/v1/rooms/join?n=${n}`, {
      method: "POST",
      headers: idHeaders(),
    });
    // A refusal means someone took the second place between the draw and the
    // press; the next poll redraws the row as full.
    if (res.ok) {
      myRoom = n;
      sim._sim_set_my_room(n);
    }
  } catch (err) {
    console.info("rooms: join failed", err);
  }
}

// The gesture belongs to the core -- a press joins the room under the cursor,
// a hold goes back to the list -- so this only carries the decision to the
// relay, exactly as src/main.cpp does on the board. Reading the raw button
// here as well is what let the press that opened the page join room 1 before
// the player had seen the list.
function pumpRoomPress() {
  // The leave is read whether or not we are in a match: holding centre works
  // from every page of a game, and walking out of one is the case that
  // matters most. Only the join is a lobby-list thing.
  if (sim._sim_take_room_leave()) void leaveRoom();
  if (peerToken) return;
  const join = sim._sim_take_room_join();
  if (join) void joinRoom(join);
}

async function leaveRoom() {
  const wasPlaying = peerToken !== "";
  myRoom = 0;
  peerToken = "";          // the seat is given up, so nothing is carried on it
  pollGeneration++;        // and the loop that was reading it stops
  pollCursor = 0;
  sim._sim_set_my_room(0);
  sim._sim_set_link(LINK.connecting);
  try {
    await fetch("/v1/rooms/leave", { method: "POST", headers: idHeaders() });
  } catch (err) {
    console.info("rooms: leave failed", err);
  }
  // Walking out of a match means going back to the list, which is a loop that
  // stopped when the match started. The core has already cleared its own
  // board; this is the transport catching up with it.
  if (wasPlaying) void roomLoop();
}

// The relay is reached through the lobby now, not by claiming a seat. A seat
// is a role in a match, and there is no match until two players have chosen
// each other -- claiming one on arrival is what turned the third person away
// instead of showing them who was here.
async function connect() {
  sim._sim_set_link(LINK.connecting);
  for (;;) {
    try {
      const res = await fetch("/v1/lobby/join", {
        method: "POST",
        headers: { ...idHeaders(), "Content-Type": "application/json" },
        body: JSON.stringify({ name: playerName }),
      });
      if (!res.ok) throw new Error(`lobby: ${res.status}`);
      const body = await res.json();
      console.info(
        `lobby: ${body.player.name}`,
        body.resume ? "-- a match of yours is still running" : "",
      );
      known = true;
      if (pendingJoin) {
        const n = pendingJoin;
        pendingJoin = 0;
        void joinRoom(n);
      }
      return;
    } catch (err) {
      // Offline, not merely connecting. With no relay there is no opponent
      // who could ever arrive, and the connecting page waits for a fact about
      // two machines rather than on a timer -- so a page told "connecting"
      // for ever is a page that can never be played. Offline is what lets the
      // core fall through and play solo, which is the whole point of the
      // simulator working with nothing else running.
      console.info("relay: not reachable, playing offline until it appears", err);
      sim._sim_set_link(LINK.offline);
      await new Promise((r) => setTimeout(r, 3000));
    }
  }
}

// The core is started BEFORE the lobby flow, not after it. Doing it after was
// the bug that hid the lobby: begin() plus a jump to the start page ran once
// the room loop had already opened the rooms page, so the page it had just
// selected was thrown away and the browser sat on the title for ever.
sim._sim_begin();
selectPage(PAGE.start);

wireNameBox();       // the box exists from the start; the name arrives next

// Asked once, the first time. After that the name is known and the box under
// the screens is where it is changed -- stopping a returning player at a
// modal to confirm the name they already have is a door with nothing behind
// it, and it made renaming yourself a two-step affair.
if (playerName === "") {
  await askName();
} else {
  el("nameModal", HTMLDivElement).hidden = true;
}
// Straight to the lobby list, before anything is polled. The title asks
// ONLINE or OFFLINE, which is a question a browser has already answered by
// being a browser -- and leaving it up meant the first press after typing a
// name was swallowed by it, taking the player to the connecting page instead
// of into a lobby.
selectPage(PAGE.rooms);
await connect();     // join the lobby; a seat comes later, from being paired
void roomLoop();     // the five lobbies, drawn on the top panel by the core

// ---- walking back into a match ----------------------------------------
//
// The board as it stands, rather than the log replayed: a result means "the
// shot you just fired", and a page that has just been reloaded fired nothing.
// The relay answers with marks that name their own cell (TMark / TDamage /
// TTurn), which the core applies without firing or answering anything.
//
// The cursor comes back with it: everything in the log is already accounted
// for in the position, so polling from the start would replay the whole match
// on top of it.
let pollCursor = 0;

async function reconnect(): Promise<boolean> {
  try {
    const res = await fetch("/v1/reconnect", { headers: { "X-Peer-Token": peerToken } });
    if (!res.ok) return false;
    const body = await res.json();
    const packets = (body.packets ?? []) as Array<
      { v: number; seq: number; src: number; dst: number; t: number; a: number; b: number }
    >;
    if (packets.length === 0) return false;
    for (const p of packets) sim._sim_receive(p.v, p.seq, p.src, p.dst, p.t, p.a, p.b);
    pollCursor = body.next ?? 0;
    console.info(`relay: rejoined lobby ${body.room} -- ${packets.length} frames of board`);
    return true;
  } catch (err) {
    console.info("relay: reconnect failed", err);
    return false;
  }
}

// ---- carrying packets ----
// The core holds no transport, so this moves them: whatever the relay has for
// us is pushed in, and whatever the core wants to say is drained out and
// posted. Both directions are pumped from the animation loop below, except
// the poll, which parks on the server until something happens.

// One poll loop at a time, and it belongs to one seat.
//
// The loop parks on the server for up to 25 seconds, so it cannot be stopped
// by clearing a token: the reply lands long after. Each loop therefore keeps
// the token it was started for and stops the moment that is no longer the
// current one -- which is what leaving a match, or losing a seat, does. Two
// loops on one seat would double-deliver every packet, and a loop from the
// last match would feed it into a core that has been cleared.
let pollGeneration = 0;

async function pollForever() {
  const mine = ++pollGeneration;
  const seat = peerToken;
  // From wherever the reconnect left the cursor: everything before it is
  // already in the position the relay handed back. It is reset with the seat,
  // so the next match starts reading its log from the beginning rather than
  // skipping the Start packets that opened it.
  let cursor = pollCursor;
  // A long poll answers the moment the opponent moves, so a shot appears as
  // fast as the network allows rather than on some local timer.
  for (;;) {
    if (mine !== pollGeneration || peerToken !== seat) return;
    try {
      const res = await fetch(`/v1/recv?since=${cursor}`, {
        headers: { "X-Peer-Token": seat },
      });
      // The seat is gone -- the relay restarted, or the seats were cleared.
      // Claim a new one rather than retrying a token nobody recognises for
      // ever, which is what the firmware does too.
      // The seat is gone: the relay restarted, or -- the ordinary case now --
      // the match ended and its room was cleared. Either way this game is
      // over, so the core is reset and the player goes back to the lobby
      // list. Keeping the board would show the last match's ships and shots
      // in what is meant to be a fresh game.
      if (res.status === 401) {
        // The verdict first. A match ends by the relay clearing the lobby,
        // which invalidates the seat -- so the 401 that tells us the game is
        // over arrives a moment after the WIN or LOSE goes up, and resetting
        // on it took the answer off the screen before it could be read.
        if (sim._sim_page() === PAGE.over) {
          for (let i = 0; i < 24 && sim._sim_page() === PAGE.over; i++) {
            // Or until they press: the verdict is worth a few seconds, not an
            // argument about how long.
            if (i > 2 && (inputMask() & M.center) !== 0) break;
            await new Promise((r) => setTimeout(r, 250));
          }
        }
        console.info("relay: seat lost, back to the lobby");
        peerToken = "";
        myRoom = 0;
        pollCursor = 0;   // the next match reads its own log from the start
        sim._sim_begin();
        sim._sim_set_my_room(0);
        sim._sim_set_link(LINK.connecting);
        selectPage(PAGE.rooms);
        await connect();
        void roomLoop();
        return;
      }
      if (!res.ok) throw new Error(`recv: ${res.status}`);
      const body = await res.json();
      cursor = body.next;
      for (const p of body.packets) {
        sim._sim_receive(p.v, p.seq, p.src, p.dst, p.t, p.a, p.b);
      }
      // Still there. Say so, or a single earlier hiccup would leave the core
      // believing the link is down for the rest of the session.
      sim._sim_set_link(LINK.online);
    } catch (err) {
      // Connecting, not offline. Offline means "there is no network here" and
      // the core takes it as licence to play alone; a hiccup on one poll is
      // nothing of the sort, and treating it that way would drop the player
      // into a solo game while their opponent waits.
      console.info("relay: poll failed, retrying", err);
      sim._sim_set_link(LINK.connecting);
      await new Promise((r) => setTimeout(r, 1000));
    }
  }
}

// Drain whatever the core produced this frame. Reading the pointer before
// calling again matters: it points at one static buffer inside the module.
// Everything the core produced this frame, in one request.
//
// Laying out a fleet produces six packets at once, and the placement code
// states the invariant outright: Ready is last, so a peer that sees Ready
// knows every Fleet is already behind it. Six separate fetches handed that
// ordering to the browser's connection pool, which does not know about it.
// One request keeps the order and costs one round trip instead of six --
// which is what the firmware has always done with its octet-stream batch.
function flushOutbound() {
  if (!peerToken) return;
  const batch: Array<Record<string, number>> = [];
  for (;;) {
    const ptr = sim._sim_take_outbound();
    if (!ptr) break;
    const w = sim.HEAPU8.subarray(ptr, ptr + 8);
    // The layout of record: v, t, src, dst, seq lo, seq hi, a, b.
    // See server/PROTOCOL.md and game::packWire().
    batch.push({
      v: w[0],
      t: w[1],
      src: w[2],
      dst: w[3],
      seq: w[4] | (w[5] << 8),
      a: w[6],
      b: w[7],
    });
  }
  if (batch.length === 0) return;

  const seat = peerToken;
  void fetch("/v1/send", {
    method: "POST",
    headers: { "X-Peer-Token": seat, "Content-Type": "application/json" },
    body: JSON.stringify(batch.length === 1 ? batch[0] : batch),
  }).catch((err) => console.info("relay: send failed", err));
}


// --- rendering -------------------------------------------------------------
const ON = [0x33, 0xcc, 0xff, 0xff];   // lit pixel
const OFF = [0x0a, 0x0e, 0x14, 0xff];  // unlit

class Panel {
  private ctx: CanvasRenderingContext2D;
  private img: ImageData;

  constructor(canvas: HTMLCanvasElement, private ptr: () => number) {
    canvas.width = W;
    canvas.height = H;
    const ctx = canvas.getContext("2d");
    if (!ctx) throw new Error("2d context unavailable");
    this.ctx = ctx;
    this.img = ctx.createImageData(W, H);
  }

  // Unpack SSD1306 page format: byte (x + (y/8)*W) holds 8 stacked pixels,
  // LSB topmost -- the exact bytes the real panel would receive over I2C.
  draw() {
    const base = this.ptr();
    const heap = sim.HEAPU8;
    const px = this.img.data;
    for (let y = 0; y < H; y++) {
      const page = (y >> 3) * W;
      const bit = 1 << (y & 7);
      for (let x = 0; x < W; x++) {
        const c = heap[base + page + x] & bit ? ON : OFF;
        const o = (y * W + x) * 4;
        px[o] = c[0]; px[o + 1] = c[1]; px[o + 2] = c[2]; px[o + 3] = c[3];
      }
    }
    this.ctx.putImageData(this.img, 0, 0);
  }
}

const byId = (id: string) => {
  const el = document.getElementById(id);
  if (!(el instanceof HTMLCanvasElement)) throw new Error(`missing canvas #${id}`);
  return el;
};

const panels = [
  new Panel(byId("top"), () => sim._sim_top()),
  new Panel(byId("bottom"), () => sim._sim_bottom()),
];

// Both panels take touches, so whichever one a thumb lands on drives the same
// five buttons -- there is no "controls" half of this page to reach for.
for (const id of ["top", "bottom"]) touchControls(byId(id));

// --- loop ------------------------------------------------------------------

// Debug hook: the page the core is on, for automated tests to read. It is a
// number on a global, not a control -- nothing in the page reads it back.
declare global {
  interface Window {
    __corePage?: number; __myTurn?: number;
    __aim?: [number, number]; __inFlight?: number;
  }
}

function frame(now: number) {
  nameBoxRefresh();
  window.__corePage = sim._sim_page();
  window.__myTurn = sim._sim_my_turn();
  window.__aim = [sim._sim_aim_col(), sim._sim_aim_row()];
  window.__inFlight = sim._sim_in_flight();
  sim._sim_set_input(inputMask());
  // Before the tick, so a press is acted on in the same frame the core sees
  // it move the cursor.
  pumpRoomPress();
  sim._sim_tick(Math.floor(now));
  // Drain after the tick, since that is when the core decides to say
  // something -- a shot fired on this frame goes out on this frame.
  flushOutbound();
  for (const p of panels) p.draw();
  requestAnimationFrame(frame);
}
requestAnimationFrame(frame);
